[project]
name = "yfinance-topix500-verification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jpholiday>=1.0.2",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "yfinance>=0.2.62",
]
