backtest:
  end_date: '2023-06-30'
  initial_capital: 10000000
  start_date: '2023-01-01'
data_source:
  cache_dir: ./data/cache
  cache_expire_hours: 24
  primary: yfinance
execution:
  commission: 0.0005
  min_commission: 100
  slippage: 0.001
logging:
  file: ./logs/quickstart.log
  format: '{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}'
  level: INFO
output:
  report_format:
  - json
  - csv
  - html
  results_dir: ./data/results/quickstart
  save_portfolio_history: true
  save_trades: true
strategy:
  addition:
    add_on_drop: true
    add_ratio: 0.5
    enabled: true
  entry:
    days_before_record: 3
    max_positions: 5
    position_size: 2000000
  exit:
    max_holding_days: 20
    stop_loss_pct: 0.1
    take_profit_on_window_fill: true
universe:
  tickers:
  - '7203'
  - '6758'
  - '9432'
