# シンプル修正版設定
# より現実的な結果を得るための最小限の調整

backtest:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_capital: 10_000_000

data_source:
  primary: "yfinance"
  cache_dir: "./data/cache"
  cache_expire_hours: 24

strategy:
  entry:
    days_before_record: 3
    position_size: 1_000_000
    max_positions: 5
  
  addition:
    enabled: false  # 買い増しを無効化（シンプル化）
    add_ratio: 0.0
    add_on_drop: false
  
  exit:
    max_holding_days: 20
    stop_loss_pct: 0.1
    take_profit_on_window_fill: false  # 窓埋め判定を無効化

execution:
  slippage: 0.005  # 0.5%（現実的な値）
  slippage_ex_date: 0.01  # 1%（権利落ち日）
  commission: 0.001  # 0.1%
  min_commission: 550
  max_commission: 1100
  tax_rate: 0.20315

universe:
  # 配当が確実にある主要銘柄のみ
  tickers:
    - "7203"  # トヨタ自動車
    - "8306"  # 三菱UFJフィナンシャル
    - "8058"  # 三菱商事

logging:
  level: "INFO"
  file: "./logs/backtest_simple.log"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"

output:
  results_dir: "./data/results/simple"
  report_format: ["json", "csv"]
  save_trades: true
  save_portfolio_history: true
