# TOPIX500全銘柄対象 - 長期バックテスト設定
# 本格的なバックテスト用の設定ファイル

backtest:
  start_date: "2010-01-01"  # 14年間の長期バックテスト
  end_date: "2024-12-31"
  initial_capital: 100_000_000  # 1億円（より現実的な運用規模）

data_source:
  primary: "yfinance"
  cache_dir: "./data/cache"
  cache_expire_hours: 168  # 1週間（大量データのため長めに設定）

strategy:
  entry:
    days_before_record: 3  # 権利確定日の3営業日前にエントリー
    position_size: 2_000_000  # 1銘柄あたり200万円（分散投資）
    max_positions: 50  # 最大50銘柄まで同時保有

  addition:
    enabled: true  # 買い増し機能を有効化
    add_ratio: 0.3  # 初期投資額の30%まで買い増し（リスク管理）
    add_on_drop: true  # 権利落ち日の下落時に買い増し

  exit:
    max_holding_days: 20  # 最大保有期間（営業日）
    stop_loss_pct: 0.08  # 損切りライン（-8%）より厳格に
    take_profit_on_window_fill: true  # 窓埋め達成で利益確定

execution:
  slippage: 0.0015  # スリッページ0.15%（流動性を考慮）
  commission: 0.00025  # 手数料0.025%（機関投資家レート）
  min_commission: 100  # 最低手数料100円

universe:
  # TOPIX500構成銘柄（業種別に主要銘柄を網羅）
  tickers:
    # 電気機器
    - "6758"  # ソニーグループ
    - "6861"  # キーエンス
    - "7751"  # キヤノン
    - "6971"  # 京セラ
    - "6954"  # ファナック
    - "6857"  # アドバンテスト
    - "6762"  # TDK
    - "6841"  # 横河電機
    - "6724"  # セイコーエプソン
    - "6753"  # シャープ
    - "6701"  # 日本電気
    - "6503"  # 三菱電機
    - "6479"  # ミネベアミツミ
    - "6902"  # デンソー
    - "6981"  # 村田製作所

    # 輸送用機器
    - "7203"  # トヨタ自動車
    - "7267"  # ホンダ
    - "7201"  # 日産自動車
    - "7261"  # マツダ
    - "7270"  # SUBARU
    - "7211"  # 三菱自動車
    - "7202"  # いすゞ自動車
    - "7269"  # スズキ
    - "7272"  # ヤマハ発動機
    - "7259"  # アイシン

    # 情報・通信業
    - "9432"  # 日本電信電話
    - "9433"  # KDDI
    - "9984"  # ソフトバンクグループ
    - "9434"  # ソフトバンク
    - "4704"  # トレンドマイクロ
    - "9613"  # NTTデータグループ
    - "3774"  # インターネットイニシアティブ
    - "4689"  # Zホールディングス
    - "4755"  # 楽天グループ
    - "2413"  # エムスリー

    # 銀行業
    - "8306"  # 三菱UFJフィナンシャル
    - "8316"  # 三井住友フィナンシャル
    - "8411"  # みずほフィナンシャル
    - "8309"  # 三井住友トラスト
    - "8354"  # ふくおかフィナンシャル
    # - "8355"  # 静岡銀行
    - "8331"  # 千葉銀行
    - "8359"  # 八十二銀行
    - "7186"  # コンコルディア・フィナンシャル
    - "7182"  # ゆうちょ銀行

    # 医薬品
    - "4502"  # 武田薬品工業
    - "4503"  # アステラス製薬
    - "4519"  # 中外製薬
    - "4523"  # エーザイ
    - "4507"  # 塩野義製薬
    - "4506"  # 住友ファーマ
    - "4568"  # 第一三共
    - "4151"  # 協和キリン
    - "4578"  # 大塚ホールディングス
    - "4521"  # 科研製薬

    # 卸売業
    - "8058"  # 三菱商事
    - "8001"  # 伊藤忠商事
    - "8031"  # 三井物産
    - "8053"  # 住友商事
    - "8002"  # 丸紅
    - "8015"  # 豊田通商
    - "8012"  # 長瀬産業
    - "2768"  # 双日
    - "7467"  # 萩原電気ホールディングス
    - "8078"  # 阪和興業

    # 小売業
    - "3382"  # セブン&アイ
    - "8267"  # イオン
    - "3092"  # ZOZO
    - "3391"  # ツルハホールディングス
    - "3088"  # マツキヨココカラ
    - "9983"  # ファーストリテイリング
    - "7532"  # パン・パシフィック
    - "3197"  # すかいらーくホールディングス
    # - "2651"  # ローソン
    - "3141"  # ウエルシアホールディングス

    # 食料品
    - "2502"  # アサヒグループ
    - "2503"  # キリンホールディングス
    - "2587"  # サントリー食品インターナショナル
    - "2801"  # キッコーマン
    - "2802"  # 味の素
    - "2914"  # 日本たばこ産業
    - "2282"  # 日本ハム
    - "2269"  # 明治ホールディングス
    - "2264"  # 森永乳業
    - "2212"  # 山崎製パン

    # 化学
    - "4063"  # 信越化学工業
    - "3407"  # 旭化成
    - "4005"  # 住友化学
    - "4183"  # 三井化学
    - "4021"  # 日産化学
    - "4188"  # 三菱ケミカルグループ
    - "4901"  # 富士フイルム
    - "4452"  # 花王
    - "4911"  # 資生堂
    - "6988"  # 日東電工

    # 機械
    - "6273"  # SMC
    - "6367"  # ダイキン工業
    - "7011"  # 三菱重工業
    - "6301"  # コマツ
    - "6305"  # 日立建機
    - "6326"  # クボタ
    - "6471"  # 日本精工
    - "6472"  # NTN
    - "6473"  # ジェイテクト
    - "7013"  # IHI

    # 建設業
    - "1812"  # 鹿島建設
    - "1802"  # 大林組
    - "1801"  # 大成建設
    - "1803"  # 清水建設
    - "1808"  # 長谷工コーポレーション
    - "1928"  # 積水ハウス
    - "1925"  # 大和ハウス工業
    - "1963"  # 日揮ホールディングス
    - "1721"  # コムシスホールディングス
    - "5233"  # 太平洋セメント

    # 不動産業
    - "8802"  # 三菱地所
    - "8801"  # 三井不動産
    - "8830"  # 住友不動産
    - "3289"  # 東急不動産ホールディングス
    - "8804"  # 東京建物
    - "8905"  # イオンモール
    - "3231"  # 野村不動産ホールディングス
    # - "8933"  # NTT都市開発
    - "8985"  # ジャパンリアルエステイト
    - "8951"  # 日本ビルファンド

    # 証券・商品先物取引業
    - "8604"  # 野村ホールディングス
    - "8601"  # 大和証券グループ本社
    - "8473"  # SBIホールディングス
    - "8628"  # 松井証券
    - "8698"  # マネックスグループ
    - "8616"  # 東海東京フィナンシャル
    - "8609"  # 岡三証券グループ
    - "7177"  # GMOフィナンシャルホールディングス

    # 保険業
    - "8766"  # 東京海上ホールディングス
    - "8725"  # MS&ADインシュアランス
    - "8630"  # SOMPOホールディングス
    - "8750"  # 第一生命ホールディングス
    - "8795"  # T&Dホールディングス
    - "8798"  # アドバンスクリエイト
    - "7157"  # ライフネット生命保険

    # 鉄鋼
    - "5401"  # 日本製鉄
    - "5411"  # JFEホールディングス
    - "5406"  # 神戸製鋼所
    - "5423"  # 東京製鐵
    - "5444"  # 大和工業
    # - "5486"  # 日立金属
    - "5541"  # 大平洋金属
    - "5463"  # 丸一鋼管

    # 非鉄金属
    - "5713"  # 住友金属鉱山
    - "5706"  # 三井金属鉱業
    - "5711"  # 三菱マテリアル
    - "5707"  # 東邦亜鉛
    - "5801"  # 古河電気工業
    - "5802"  # 住友電気工業
    - "5803"  # フジクラ
    - "3436"  # SUMCO

    # ガラス・土石製品
    - "5201"  # AGC
    - "5202"  # 日本板硝子
    - "5301"  # 東海カーボン
    - "5332"  # TOTO
    - "5333"  # 日本ガイシ
    - "5334"  # 日本特殊陶業
    - "4204"  # 積水化学工業
    - "5214"  # 日本電気硝子

    # 石油・石炭製品
    - "5019"  # 出光興産
    - "5020"  # ENEOSホールディングス
    - "5021"  # コスモエネルギー
    # - "5008"  # 東亜石油
    - "5015"  # ビーピー・カストロール

    # ゴム製品
    - "5101"  # 横浜ゴム
    - "5108"  # ブリヂストン
    - "5110"  # 住友ゴム工業
    - "5195"  # バンドー化学
    - "4004"  # レゾナック・ホールディングス

    # 海運業
    - "9101"  # 日本郵船
    - "9104"  # 商船三井
    - "9107"  # 川崎汽船
    - "9110"  # NSユナイテッド海運
    - "9115"  # 明治海運

    # 空運業
    - "9201"  # 日本航空
    - "9202"  # ANAホールディングス
    - "9206"  # スターフライヤー

    # 鉄道・バス
    - "9020"  # 東日本旅客鉄道
    - "9021"  # 西日本旅客鉄道
    - "9022"  # 東海旅客鉄道
    - "9001"  # 東武鉄道
    - "9005"  # 東急
    - "9007"  # 小田急電鉄
    - "9008"  # 京王電鉄
    - "9009"  # 京成電鉄
    - "9024"  # 西武ホールディングス
    - "9044"  # 南海電気鉄道

    # 電気・ガス業
    - "9501"  # 東京電力ホールディングス
    - "9502"  # 中部電力
    - "9503"  # 関西電力
    - "9504"  # 中国電力
    - "9505"  # 北陸電力
    - "9506"  # 東北電力
    - "9507"  # 四国電力
    - "9508"  # 九州電力
    - "9509"  # 北海道電力
    - "9531"  # 東京ガス
    - "9532"  # 大阪ガス

    # サービス業
    - "4661"  # オリエンタルランド
    - "6098"  # リクルートホールディングス
    - "2413"  # エムスリー
    - "2181"  # パーソルホールディングス
    - "4751"  # サイバーエージェント
    - "9735"  # セコム
    - "2331"  # 綜合警備保障
    - "4732"  # ユー・エス・エス
    - "9697"  # カプコン
    - "7832"  # バンダイナムコホールディングス

    # その他製品
    - "7974"  # 任天堂
    - "7731"  # ニコン
    - "7733"  # オリンパス
    - "7762"  # シチズン時計
    - "7951"  # ヤマハ
    - "7911"  # 凸版印刷
    - "7912"  # 大日本印刷
    - "4543"  # テルモ
    - "4902"  # コニカミノルタ
    - "7752"  # リコー

    # 精密機器
    - "4543"  # テルモ
    - "7701"  # 島津製作所
    - "6645"  # オムロン
    - "6869"  # シスメックス
    - "7735"  # SCREENホールディングス
    - "6146"  # ディスコ
    - "7747"  # 朝日インテック
    - "4062"  # イビデン

    # 繊維製品
    - "3401"  # 帝人
    - "3402"  # 東レ
    - "3101"  # 東洋紡
    - "3103"  # ユニチカ
    - "3104"  # 富士紡ホールディングス

    # パルプ・紙
    - "3861"  # 王子ホールディングス
    - "3863"  # 日本製紙
    - "3865"  # 北越コーポレーション
    - "3880"  # 大王製紙
    - "3891"  # ニッポン高度紙工業

    # 倉庫・運輸関連業
    - "9301"  # 三菱倉庫
    - "9302"  # 三井倉庫ホールディングス
    - "9303"  # 住友倉庫
    - "9304"  # 澁澤倉庫
    # - "9062"  # 日本通運
    - "9064"  # ヤマトホールディングス
    - "9143"  # SGホールディングス
    - "9065"  # 山九

    # その他金融業
    - "8253"  # クレディセゾン
    - "8591"  # オリックス
    - "8593"  # 三菱HCキャピタル
    - "8566"  # リコーリース
    - "8572"  # アコム
    - "8570"  # イオンフィナンシャルサービス
    - "8697"  # 日本取引所グループ

    # 鉱業
    - "1605"  # INPEX
    - "1662"  # 石油資源開発
    - "1515"  # 日鉄鉱業

    # 水産・農林業
    - "1332"  # 日本水産
    - "1333"  # マルハニチロ
    - "1377"  # サカタのタネ
    - "1379"  # ホクト

logging:
  level: "INFO"
  file: "./logs/topix500_backtest.log"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"

output:
  results_dir: "./data/results/topix500_full"
  report_format: ["json", "csv", "html"]
  save_trades: true
  save_portfolio_history: true

# パフォーマンス最適化設定
optimization:
  parallel_processing: true  # 並列処理を有効化
  batch_size: 50  # データ取得のバッチサイズ
  memory_limit_gb: 16  # メモリ使用量制限

# リスク管理設定
risk_management:
  max_sector_exposure: 0.3  # セクターあたり最大エクスポージャー30%
  max_single_stock_exposure: 0.05  # 1銘柄あたり最大5%
  portfolio_rebalance_frequency: "monthly"  # 月次リバランス
